### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by echofriend** [AbhinavRobinson/Electron-Screen-Recorder#7]
Do you have a setup, guide or video on how to install and use?

Thanks

**Comment by AbhinavRobinson** [comment]
Its a simple app, you can use `npm install`, then build the app using `npm run make`

test it out using `npm start`

alt you can yarn too

**Comment by AbhinavRobinson** [comment]
![image](https://user-images.githubusercontent.com/32090909/106993045-dd962e00-679f-11eb-9cb1-bb429fd0861f.png)

After  `npm i`

using `npm start`

**Comment by AbhinavRobinson** [comment]
![image](https://user-images.githubusercontent.com/32090909/106993327-7af16200-67a0-11eb-96e1-88dff86e9c9b.png)

After running `npm run make` you will find a generated out folder.

(ps: npm run make requires 'rpm', if not installed, use `sudo apt install rpm`)

**Comment by AbhinavRobinson** [comment]
Documentation is provided now, hope this solves your issue! 

Happy Coding.
